env:
  node: true
  es2021: true
  jest/globals: true
extends:
  - airbnb-base
plugins:
  - jest
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  import/extensions: [0, { <js>: 'always' }]
